"""add_estimated_duration_to_tasks

Revision ID: 33cca10ba042
Revises: 002
Create Date: 2026-01-10 20:32:01.796764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33cca10ba042'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('estimated_duration', sa.Integer(), nullable=True))
    op.drop_index('ix_users_oauth_id', table_name='users')
    op.create_unique_constraint(None, 'users', ['oauth_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_oauth_id', 'users', ['oauth_id'], unique=True)
    op.drop_column('tasks', 'estimated_duration')
    # ### end Alembic commands ###
