"""add_duration_and_start_date_to_habits

Revision ID: b30fd05bf435
Revises: 33cca10ba042
Create Date: 2026-01-11 10:45:09.217013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b30fd05bf435'
down_revision = '33cca10ba042'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('duration_days', sa.Integer(), nullable=True))
    op.add_column('habits', sa.Column('start_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'start_date')
    op.drop_column('habits', 'duration_days')
    # ### end Alembic commands ###
